GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5NzQ5NTU3MCwiZXhwIjoxNTk3NDk1NTgwfQ.aacEONUCQCJjpDAhrx0iqSMA7fCx3jbtH3uPE3miuWU
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5NzQ5NTQwMSwiZXhwIjoxNTk3NDk1NDExfQ.YOB41Lx6iK9ZBtU6SHb5wKSnKKH_iNlrhIyy3XMQ8-o"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5NzQ5NTUzNH0.CrYwep8X42jRwUIu32o1msfLVJeURDA65NvB1NajbS4"
}