GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTU5NzYwMDY4MSwiZXhwIjoxNTk3NjQzODgxfQ.Z3GjEyVfCcrcV-gU8n6BynPUn9g4d34r9hY8CmCvUiM
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTU5NzYwMDU5MSwiZXhwIjoxNTk3Njg2OTkxfQ.IwVVplO1jihavl9WCIRvsxsAuLMBi1ZuxOQyJ1541Yc"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "test"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTU5NzYwMDU5MSwiZXhwIjoxNTk3Njg2OTkxfQ.IwVVplO1jihavl9WCIRvsxsAuLMBi1ZuxOQyJ1541Yc"
}